"""Build a full XFCE theme package from config."""

from __future__ import annotations

import re
import shutil
from pathlib import Path

from .config import ThemeConfig
from .palette import REFERENCE_COLORS, recolor_text
from .xfwm4_gen import generate_xfwm4

TEXT_SUFFIXES = {".css", ".gtkrc", ".theme", ".html", ".themerc", ".gtkrc", ""}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _theme_output_root(config: ThemeConfig, repo_root: Path) -> Path:
    return repo_root / config.output_dir / config.name


def _icon_output_root(config: ThemeConfig, repo_root: Path) -> Path:
    return repo_root / config.output_dir / "icons" / config.icon_theme_name


def _menu_icon_svg(ring: str, fill: str, label: str) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" role="img" aria-label="{label}">
  <path fill="none" stroke="{ring}" stroke-width="16"
        d="M128 32a96 96 0 1 1 0 192 96 96 0 0 1 0-192z"/>
  <path fill="{fill}"
        d="M192 120h-49l23.71-35.56A8 8 0 0 0 160 72H96a8 8 0 0 0-6.66 12.44L113.05 120H64a8 8 0 0 0-6.66 12.44l32 48a8 8 0 0 0 13.32 0l25.34-38 25.34 38a8 8 0 0 0 13.32 0l32-48A8 8 0 0 0 199.05 124.23ZM145.05 88 128 113.58 111 88ZM96 161.58 79 136h34.1Zm64 0L143 136h34.1Z"/>
</svg>
"""


def _apply_corner_style(text: str, square: bool) -> str:
    if square:
        return text
    return re.sub(
        r"border-radius:\s*0\s*;",
        "border-radius: 4px;",
        text,
    )


def _write_index_theme(path: Path, config: ThemeConfig) -> None:
    icon_name = config.icon_theme_name
    content = f"""[Desktop Entry]
Type=X-GNOME-Metatheme
Name={config.display_name}
Comment={config.comment}
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme={config.name}
MetacityTheme={config.name}
IconTheme={icon_name}
CursorTheme=default
ButtonLayout=menu:minimize,maximize,close

[Xfce]
Xfwm4Theme={config.name}
"""
    path.write_text(content, encoding="utf-8")


def _write_icon_index(path: Path, config: ThemeConfig) -> None:
    content = f"""[Icon Theme]
Name={config.icon_theme_name}
Comment=Menu icons for {config.display_name}
Inherits=Adwaita,hicolor
Example=start-here

Directories=scalable/places,scalable/apps

[scalable/places]
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/apps]
Size=16
MinSize=16
MaxSize=256
Type=Scalable
"""
    path.write_text(content, encoding="utf-8")


def _recolor_tree(target: Path, config: ThemeConfig) -> None:
    square = config.options.square_corners
    for path in target.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".css", ".html"} and path.name not in {"gtkrc", "themerc"}:
            continue
        text = path.read_text(encoding="utf-8")
        text = recolor_text(text, REFERENCE_COLORS, config.colors)
        text = _apply_corner_style(text, square)
        path.write_text(text, encoding="utf-8")


def build_theme(config: ThemeConfig, repo_root: Path | None = None) -> Path:
    repo_root = repo_root or _repo_root()
    base = repo_root / "themes" / config.base_theme
    if not base.is_dir():
        raise FileNotFoundError(f"Base theme not found: {base}")

    out = _theme_output_root(config, repo_root)
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(base, out)

    _recolor_tree(out, config)
    generate_xfwm4(out / "xfwm4", config.colors)
    _write_index_theme(out / "index.theme", config)

    gtkrc = out / "gtk-2.0" / "gtkrc"
    if gtkrc.exists():
        text = gtkrc.read_text(encoding="utf-8")
        text = re.sub(r'gtk-theme-name = "[^"]+"', f'gtk-theme-name = "{config.name}"', text)
        text = recolor_text(text, REFERENCE_COLORS, config.colors)
        gtkrc.write_text(text, encoding="utf-8")

    readme = out / "README.md"
    readme.write_text(
        f"# {config.display_name}\n\n"
        f"{config.comment}\n\n"
        f"Generated by **XFCE Theme Forge**. Rebuild with:\n\n"
        f"```bash\npython tools/xfce-theme-forge/theme-forge.py build configs/{config.slug}.json\n```\n",
        encoding="utf-8",
    )

    if config.options.generate_menu_icon:
        build_icons(config, repo_root, svg_only=False)

    return out


def build_icons(config: ThemeConfig, repo_root: Path | None = None, svg_only: bool = False) -> Path:
    repo_root = repo_root or _repo_root()
    icon_root = _icon_output_root(config, repo_root)
    if icon_root.exists():
        shutil.rmtree(icon_root)

    ring = config.options.menu_icon_ring
    fill = config.options.menu_icon_fill
    svg = _menu_icon_svg(ring, fill, config.display_name)

    places = icon_root / "scalable" / "places"
    apps = icon_root / "scalable" / "apps"
    places.mkdir(parents=True, exist_ok=True)
    apps.mkdir(parents=True, exist_ok=True)

    (places / "start-here.svg").write_text(svg, encoding="utf-8")
    slug = config.slug.lower()
    (apps / f"{slug}-menu.svg").write_text(svg, encoding="utf-8")
    _write_icon_index(icon_root / "index.theme", config)

    pixmap_dir = repo_root / config.output_dir / "pixmaps"
    pixmap_dir.mkdir(parents=True, exist_ok=True)
    pixmap_name = f"{config.name}.svg"
    (pixmap_dir / pixmap_name).write_text(svg, encoding="utf-8")

    return icon_root


def build_preview(config: ThemeConfig, repo_root: Path | None = None) -> Path:
    repo_root = repo_root or _repo_root()
    theme_dir = _theme_output_root(config, repo_root)
    preview_src = theme_dir / "preview.html"
    if not preview_src.exists():
        preview_src = repo_root / "themes" / config.base_theme / "preview.html"
    text = preview_src.read_text(encoding="utf-8")
    text = recolor_text(text, REFERENCE_COLORS, config.colors)
    text = text.replace("Nocturn", config.display_name)
    out = theme_dir / "preview.html"
    out.write_text(text, encoding="utf-8")
    return out
