"""Load and validate theme forge config files."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .palette import PRESETS, REFERENCE_COLORS, merge_colors


@dataclass
class ThemeOptions:
    square_corners: bool = True
    whisker_menu: bool = True
    generate_menu_icon: bool = True
    menu_icon_ring: str = "#cccccc"
    menu_icon_fill: str = "#40916c"
    icon_theme_name: str | None = None  # defaults to theme name


@dataclass
class ThemeConfig:
    name: str
    display_name: str
    comment: str
    colors: dict[str, str]
    options: ThemeOptions = field(default_factory=ThemeOptions)
    output_dir: str = "dist"
    base_theme: str = "Nocturn"

    @property
    def slug(self) -> str:
        return self.name.replace(" ", "-")

    @property
    def icon_theme_name(self) -> str:
        return self.options.icon_theme_name or self.name


def _load_raw(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    suffix = path.suffix.lower()
    if suffix in {".json", ".theme"}:
        return json.loads(text)
    if suffix in {".yaml", ".yml"}:
        try:
            import yaml  # type: ignore
        except ImportError as exc:
            raise RuntimeError(
                "PyYAML is required for .yaml configs. Install with: pip install pyyaml\n"
                "Or use a .json config instead."
            ) from exc
        return yaml.safe_load(text)
    raise ValueError(f"Unsupported config format: {path.suffix}")


def _options_from_dict(data: dict[str, Any] | None) -> ThemeOptions:
    data = data or {}
    opts = ThemeOptions()
    for key in (
        "square_corners",
        "whisker_menu",
        "generate_menu_icon",
    ):
        if key in data:
            setattr(opts, key, bool(data[key]))
    for key in ("menu_icon_ring", "menu_icon_fill", "icon_theme_name"):
        if key in data and data[key] is not None:
            setattr(opts, key, str(data[key]))
    if opts.menu_icon_fill == "#40916c" and "colors" in data:
        pass
    return opts


def load_config(path: Path) -> ThemeConfig:
    raw = _load_raw(path)
    name = str(raw.get("name", "")).strip()
    if not name:
        raise ValueError("Config must include 'name'")

    preset = raw.get("preset")
    base_colors = PRESETS.get(preset, REFERENCE_COLORS) if preset else REFERENCE_COLORS
    colors = merge_colors(base_colors, raw.get("colors") or {})

    opts = _options_from_dict(raw.get("options"))
    if "colors" in raw and raw["colors"]:
        accent_bright = colors.get("accent_bright")
        if accent_bright and opts.menu_icon_fill == "#40916c":
            opts.menu_icon_fill = accent_bright

    return ThemeConfig(
        name=name,
        display_name=str(raw.get("display_name", name)),
        comment=str(
            raw.get(
                "comment",
                f"XFCE/GTK theme generated by XFCE Theme Forge",
            )
        ),
        colors=colors,
        options=opts,
        output_dir=str(raw.get("output_dir", "dist")),
        base_theme=str(raw.get("base_theme", "Nocturn")),
    )


def save_config(path: Path, config: ThemeConfig) -> None:
    payload = {
        "name": config.name,
        "display_name": config.display_name,
        "comment": config.comment,
        "output_dir": config.output_dir,
        "base_theme": config.base_theme,
        "colors": config.colors,
        "options": {
            "square_corners": config.options.square_corners,
            "whisker_menu": config.options.whisker_menu,
            "generate_menu_icon": config.options.generate_menu_icon,
            "menu_icon_ring": config.options.menu_icon_ring,
            "menu_icon_fill": config.options.menu_icon_fill,
            "icon_theme_name": config.options.icon_theme_name,
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix.lower() in {".yaml", ".yml"}:
        try:
            import yaml  # type: ignore
        except ImportError as exc:
            raise RuntimeError("PyYAML required to write YAML configs") from exc
        path.write_text(yaml.dump(payload, sort_keys=False), encoding="utf-8")
    else:
        path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def new_config(name: str, preset: str = "nocturn") -> ThemeConfig:
    if preset not in PRESETS:
        raise ValueError(f"Unknown preset '{preset}'. Choose from: {', '.join(PRESETS)}")
    colors = dict(PRESETS[preset])
    opts = ThemeOptions(menu_icon_fill=colors["accent_bright"])
    return ThemeConfig(
        name=name,
        display_name=name,
        comment=f"{name} — XFCE theme built with XFCE Theme Forge",
        colors=colors,
        options=opts,
    )
