"""Generate xfwm4 pixmap assets for a theme."""

from __future__ import annotations

from pathlib import Path

TITLE_H = 30
TITLE_W = 4

CLOSE = [
    "            ",
    "  ..    ..  ",
    "   ..  ..   ",
    "    ....    ",
    "     ..     ",
    "    ....    ",
    "   ..  ..   ",
    "  ..    ..  ",
    "            ",
    "            ",
    "            ",
    "            ",
]
HIDE = [
    "            ",
    "            ",
    "            ",
    "            ",
    "  ........  ",
    "  ........  ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
    "            ",
]
MAX = [
    "            ",
    "  ........  ",
    "  ........  ",
    "  ........  ",
    "  ........  ",
    "  ........  ",
    "  ........  ",
    "  ........  ",
    "            ",
    "            ",
    "            ",
    "            ",
]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _solid_tile(name: str, w: int, h: int, color_sym: str) -> str:
    lines = [
        "/* XPM */",
        f'static char * {name}[] = {{',
        f'"{w} {h} 2 1",',
        '"  c None",',
        f'"@  c {color_sym}",',
    ]
    row = "@" * w
    lines.extend(f'"{row}",' for _ in range(h))
    lines.append("};")
    return "\n".join(lines) + "\n"


def _window_button(name: str, glyph_rows: list[str], fg: str) -> str:
    lines = [
        "/* XPM */",
        f'static char * {name}[] = {{',
        f'"{len(glyph_rows)} {len(glyph_rows)} 2 1",',
        '"  c None",',
        f'". c {fg}",',
    ]
    for row in glyph_rows:
        lines.append(f'"{row}",')
    lines.append("};")
    return "\n".join(lines) + "\n"


def generate_xfwm4(xfwm_dir: Path, colors: dict[str, str]) -> None:
    surface = colors["surface"]
    bg_alt = colors["bg_alt"]
    bg = colors["bg"]
    fg = colors["fg"]
    fg_dim = colors["fg_dim"]
    accent_bright = colors["accent_bright"]
    accent_glow = colors["accent_glow"]
    error = colors["error"]
    border_subtle = colors["border_subtle"]
    fg_bright = colors["fg_bright"]

    themerc = f"""# Generated by XFCE Theme Forge

border.width=1
border.top=2
button_offset=4
button_spacing=2
full_width_title=true
maximized_shadow=false
rounded_bottom=false
rounded_top=false
shadow_delta_height=0
shadow_delta_width=0
shadow_delta_x=0
shadow_delta_y=0
show_app_icon=false
title_alignment=center
title_font=Sans 9
title_horizontal_offset=4
title_shadow_active=false
title_shadow_inactive=false
title_vertical_offset_active=1
title_vertical_offset_inactive=2

active_text_color={fg_bright}
inactive_text_color={fg_dim}
active_text_shadow_color={bg}
inactive_text_shadow_color={bg}
active_border_color={accent_bright}
inactive_border_color={border_subtle}
active_color_1={surface}
active_color_2={bg_alt}
inactive_color_1={bg_alt}
inactive_color_2={bg}
"""
    _write(xfwm_dir / "themerc", themerc)

    top_active = f"""/* XPM */
static char * top_active_xpm[] = {{
"4 2 3 1",
"  c None",
"G c {accent_bright}",
"B c {surface} s active_color_1",
"GGGG",
"BBBB"}};
"""
    top_inactive = f"""/* XPM */
static char * top_inactive_xpm[] = {{
"4 2 2 1",
"  c None",
"B c {bg_alt} s inactive_color_1",
"BBBB",
"BBBB"}};
"""
    _write(xfwm_dir / "top-active.xpm", top_active)
    _write(xfwm_dir / "top-inactive.xpm", top_inactive)

    for i in range(1, 6):
        _write(
            xfwm_dir / f"title-{i}-active.xpm",
            _solid_tile(f"title_{i}_active_xpm", TITLE_W, TITLE_H, f"{surface} s active_color_1"),
        )
        _write(
            xfwm_dir / f"title-{i}-inactive.xpm",
            _solid_tile(f"title_{i}_inactive_xpm", TITLE_W, TITLE_H, f"{bg_alt} s inactive_color_1"),
        )

    for side, sym_a, sym_i, col_a, col_i in [
        ("left", "active_color_2", "inactive_color_2", bg_alt, bg),
        ("right", "active_color_2", "inactive_color_2", bg_alt, bg),
        ("bottom", "active_color_2", "inactive_color_2", bg_alt, bg),
    ]:
        _write(xfwm_dir / f"{side}-active.xpm", _solid_tile(f"{side}_active_xpm", 4, 4, f"{col_a} s {sym_a}"))
        _write(xfwm_dir / f"{side}-inactive.xpm", _solid_tile(f"{side}_inactive_xpm", 4, 4, f"{col_i} s {sym_i}"))

    for corner, sym_a, sym_i, col_a, col_i in [
        ("top-left", "active_color_1", "inactive_color_1", surface, bg_alt),
        ("top-right", "active_color_1", "inactive_color_1", surface, bg_alt),
        ("bottom-left", "active_color_2", "inactive_color_2", bg_alt, bg),
        ("bottom-right", "active_color_2", "inactive_color_2", bg_alt, bg),
    ]:
        slug = corner.replace("-", "_")
        _write(xfwm_dir / f"{corner}-active.xpm", _solid_tile(f"{slug}_active_xpm", 4, 4, f"{col_a} s {sym_a}"))
        _write(xfwm_dir / f"{corner}-inactive.xpm", _solid_tile(f"{slug}_inactive_xpm", 4, 4, f"{col_i} s {sym_i}"))

    for btn, glyph in [("close", CLOSE), ("hide", HIDE), ("maximize", MAX)]:
        for state, color in [
            ("active", fg),
            ("inactive", fg_dim),
            ("prelight", accent_bright if btn != "close" else error),
            ("pressed", accent_glow if btn != "close" else error),
        ]:
            _write(xfwm_dir / f"{btn}-{state}.xpm", _window_button(f"{btn}_{state}_xpm", glyph, color))
